[package]
name = "floem-vger"
description = "Unofficial vger fork for Floem"
version = "0.3.1"
license = "MIT"
readme = "README.md"
authors = ["Taylor Holliday <taylor@audulus.com>"]
repository = "https://github.com/audulus/vger-rs"
edition = "2024"


[dependencies]
wgpu = "27"
euclid = "0.22"
fontdue = "0.9"
rect_packer = "0.2"


[dev-dependencies]
png = "0.17"
futures = "0.3"
futures-intrusive = "0.5"
svg = "0.13"
rand = "0.8"
fontdue = "0.9"
